### ISSUE TITLE
empty css files import filename strings?

### ISSUE THREAD

**Issue by ianstormtaylor** [duojs/duo#119]
Looks like if a CSS file is empty and you import it, then instead of just importing nothing, it imports the name of the file itself. For example:
###### index.css

``` css
@import './other.css';

body {
  color: red;
}
```
###### other.css

``` css


```
###### build.css

``` css
/other.css

body {
  color: red;
}
```
