### ISSUE TITLE
failing to build css on specific image url

### ISSUE THREAD

**Issue by lancejpollard** [duojs/duo#181]
When a CSS file has this in it:

``` css
.SelectField-caret {
  background: url("images/caret-grey.svg") no-repeat center #FCFAF5;
  height: 30px;
  width: 30px;
  position: absolute;
  bottom: 11px;
  right: 10px;
  display: block;
  pointer-events: none;
}
```

It errors out like this:

```
error : Error: { [Error: Command failed: /bin/sh -c git ls-remote --tags --heads https://<token>@github.com/images/caret-grey.svg
remote: Repository not found.
fatal: repository 'https://<token>@github.com/images/caret-grey.svg/' not found
]
  killed: false,
  code: 128,
  signal: null,
  cmd: '/bin/sh -c git ls-remote --tags --heads https://<token>@github.com/images/caret-grey.svg' }
    at error (/Users/lancejpollard/dev/segmentio/app/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:167:10)
    at /Users/lancejpollard/dev/segmentio/app/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:68:37
    at ChildProcess.exithandler (child_process.js:736:5)
    at ChildProcess.EventEmitter.emit (events.js:110:17)
    at maybeClose (child_process.js:992:16)
    at Socket.<anonymous> (child_process.js:1142:11)
    at Socket.EventEmitter.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

If you just add a `./` at the start of the URL, it works:

``` css
.SelectField-caret {
  background: url("./images/caret-grey.svg") no-repeat center #FCFAF5;
  height: 30px;
  width: 30px;
  position: absolute;
  bottom: 11px;
  right: 10px;
  display: block;
  pointer-events: none;
}
```

Should both cases be supported or no? It worked both ways on component.

Thought this might be in duo-pack but it doesn't look it's there. Any suggestions where to take a look?

**Comment by darsain** [comment]
I'm still having this issue. Here is the code:

```css
@font-face {
  font-family: 'foo';
  src: url("../font/foo.eot");
  font-weight: normal;
  font-style: normal;
}
```

And I'm getting:

```
fatal: repository 'https://<token>@github.com/font/foo.eot/' not found
```

The `../font/foo.eot` path doesn't exist if you check it from within the build cwd. It only exists when resolved from within the build destination directory, which is unknown to the builder beforehand, so *file exists* check won't work here.

In other words, imagine this folder structure:

```
build/
 └ test.css
font/
 └ foo.eot
test.css
```

And command:

```bash
duo test.css
```

How to handle this?

**Comment by stephenmathieson** [comment]
something looks wrong here.  based on your folder structure, shouldn't your css look like:

```css
@font-face {
  font-family: 'foo';
  src: url("./font/foo.eot");
  font-weight: normal;
  font-style: normal;
}
```
