### ISSUE TITLE
stdin and assets

### ISSUE THREAD

**Issue by stephenmathieson** [duojs/duo#217]
looks like we've still got some weird behaviour with stdin/assets:

**index.css**

``` css
body {
  background: url('./images/duo.png');
}
```

builds fine:

``` sh
$ bin/duo -t css < index.css > out.css

     building : from stdin
        built : from stdin
```

but incorrectly writes:

**out.css**

``` css
body {
  background: url('/images/duo.png');
}
```

as `duo.png` is actually in `./build/images/`.

not sure if this is too edge-casey to matter, but thought i'd raise as an issue as the it confused me for a sec haha
