### ISSUE TITLE
Local CSS asset paths aren't working

### ISSUE THREAD

**Issue by lancejpollard** [duojs/duo#334]
It's sort of complicated to describe, here is a repo that demonstrates the issue:

https://github.com/duo-fixture/relative-css

To test it out:

```
make
```

Then look at https://github.com/duo-fixture/relative-css/blob/master/apps/blog/build/build.css.

So here is the tree of files in that project after you build:

```
├── apps
│   └── blog
│       ├── build
│       │   └── build.css
│       ├── index.css
│       └── lib
│           └── icons
│               ├── assets
│               │   └── logo.svg
│               └── index.css
├── build
│   ├── apps
│   │   └── blog
│   │       └── lib
│   │           └── icons
│   │               └── assets
│   │                   └── logo.svg -> ./apps/blog/lib/icons/assets/logo.svg
│   └── components
│       └── logo-wordpress@master
│           └── images
│               ├── logo-black.svg -> ./components/logo-wordpress@master/images/logo-black.svg
│               ├── logo-white.svg -> ./components/logo-wordpress@master/images/logo-white.svg
│               └── logo.svg -> ./components/logo-wordpress@master/images/logo.svg
└── components
    ├── duo.json
    ├── logo-logo@0.0.1
    │   ├── Makefile
    │   ├── Readme.md
    │   ├── component.json
    │   └── index.css
    └── logo-wordpress@master
        ├── Makefile
        ├── component.json
        ├── images
        │   ├── logo-black.svg
        │   ├── logo-white.svg
        │   └── logo.svg
        └── index.css
```

The first thing to notice is the top-level `./build` folder. It has both `build/apps` and `build/components`, and basically copies the file path for every asset. This means that, for every asset (local or remote asset), it will get copied to the `./build` folder.

Then I am writing out the final CSS file to `apps/blog/build/build.css`. That CSS writes the local asset and remote asset _differently_, check it out:

``` css
.logo[data-logo="WordPress"][data-color="white"] > * {
  background-image: url(../../components/logo-wordpress@master/images/logo-white.svg);
}

.logo {
  background: url('lib/icons/assets/logo.svg');
}
```

To get this local asset working, it should probably look like this:

``` css
.logo[data-logo="WordPress"][data-color="white"] > * {
  background-image: url(../../components/logo-wordpress@master/images/logo-white.svg);
}

.logo {
  background: url('../../build/apps/blog/lib/icons/assets/logo.svg');
}
```

That would at least make it so local assets work.

But TBH that is a bit weird, and it seems that the asset copying isn't quite right even for the remote assets.

Instead, it seems like the `apps/blog/build/build.css` should look like this:

``` css
.logo[data-logo="WordPress"][data-color="white"] > * {
  background-image: url(./components/logo-wordpress@master/images/logo-white.svg);
}

.logo {
  background: url('./lib/icons/assets/logo.svg');
}
```

Where that `relative-css` repo would instead have this final structure:

```
├── apps
│   └── blog
│       ├── build
│       │   ├── build.css
│       │   ├── components
│       │   │   └── logo-wordpress@master
│       │   │       └── images
│       │   │           ├── logo-black.svg -> ./components/logo-wordpress@master/images/logo-black.svg
│       │   │           ├── logo-white.svg -> ./components/logo-wordpress@master/images/logo-white.svg
│       │   │           └── logo.svg -> ./components/logo-wordpress@master/images/logo.svg
│       │   └── lib
│       │       └── icons
│       │           └── assets
│       │               └── logo.svg -> ./apps/blog/lib/icons/assets/logo.svg
│       ├── index.css
│       └── lib
│           └── icons
│               ├── assets
│               │   └── logo.svg
│               └── index.css
└── components
    ├── duo.json
    ├── logo-logo@0.0.1
    │   ├── Makefile
    │   ├── Readme.md
    │   ├── component.json
    │   └── index.css
    └── logo-wordpress@master
        ├── Makefile
        ├── component.json
        ├── images
        │   ├── logo-black.svg
        │   ├── logo-white.svg
        │   └── logo.svg
        └── index.css
```

Thoughts?
