### ISSUE TITLE
Unwanted styles dependency resolution

### ISSUE THREAD

**Issue by darsain** [duojs/duo#447]
Project: https://gist.github.com/anonymous/807ee9ea89692a000e6d

To test:

```
git clone https://gist.github.com/807ee9ea89692a000e6d.git
cd 807ee9ea89692a000e6d
duo -S test.css
```

The expected output would be:

```css
.a { color: red; }
.test { color: blue; }
```

but instead, we get the remaining styles from `component.json:styles` array appended at the end, resulting in:

```css
.a { color: red; }
.test { color: blue; }
.b { color: green; }
```

---

And while I'm at it, how would you build styles for this component with Duo, assuming there is no `test.css`, just styles split into separate files?

Is there some shorthand like `new Duo(__dirname).entry('styles')` that would build styles from `component.json` located at `__dirname`? I haven't found anything in docs regarding this.
